### ISSUE TITLE
Test Cloud Foundry Go client

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/disrupt-o-meter#2] opened 2019-01-08 12:19 UTC
Verify whether https://github.com/cloudfoundry-community/go-cfclient is an option to be used to access Cloud Foundry, especially if we can mock it properly.

**Comment by LynxPlay101** [comment] 2019-01-14 15:52
Duplicate of #15

**Closed** 2019-01-14 15:53 UTC
